Algoritmo "Meu primeiro algoritmo"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Fernanda Marinho
// Data atual  : 19/04/2020
Var
// Seção de Declarações das variáveis 
 //primeiro nome
 //segundo nome
 //idade
 //cidade
 //endereco
 
 primeiroNome, segundoNome: caractere;
 idade: inteiro;
 

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  nota <- 100
  escreva ("Resultado: ", nota)

Fimalgoritmo